build: update to eslint v9
jsx-eslint/eslint-plugin-jsx-a11y pull request #1009
Opened 2024-08-30 17:57 UTC by michaelfaith

This change adds support for eslint v9.  All three example projects have been updated to use the latest eslint, and the root package's dev and peer deps have been updated. 

In order to make this work with both v9 and older versions, I had to update the parser options helper to adjust the config passed into the `RuleTester`. It was also necessary update jest to a newer version, in order to resolve eslint's use of `node:fs/promises`. 

![image](https://github.com/user-attachments/assets/ba4ec6ea-20a9-427d-b3ea-b0dbbdcb78aa)

Note: the removed test cases are exact duplicates of other tests.  v9 fails tests when its determined to be an exact duplicate.

Closes: #978

2024-08-30 18:04 UTC, michaelfaith commented on package.json
> +    "pretest": "npm run flow",
This was necessary since the root eslint config would need to be overhauled in order to run lint for the whole project with v9, and that didn't seem appropriate to be in scope for this change.  Not sure if that means linting should be done explicitly in CI with the default eslint version.

2024-08-30 18:09 UTC, ljharb requested changes

2024-08-30 18:09 UTC, ljharb commented on __tests__/src/rules/no-static-element-interactions-test.js
> -  { code: '<link onClick={() => {}} href="#" />;' },
none of the removals in this file seem like duplicates

2024-08-30 18:09 UTC, ljharb commented on package.json
> +    "jest": "^29.7.0",
we can't upgrade jest, because jest 24 is the last version that supports node 6.

2024-08-30 18:10 UTC, ljharb commented on package.json
> +    "pretest": "npm run flow",
can the lint script just run `npx eslint@8 --ext=js,mjs,cjs,ts,tsx .`, rather than this change?

2024-08-30 18:49 UTC, michaelfaith commented on package.json
> +    "pretest": "npm run flow",
Done

2024-08-30 18:53 UTC, michaelfaith commented on package.json
> +    "jest": "^29.7.0",
Hmm. Ok, but jest 24 isn't able to resolve `node:fs/promises` which eslint uses (so we hit this when importing `RuleTester` from eslint.  I could map node:fs/eslint to something like fs-extra using jest's `moduleNameMapper`?  So the project is never going higher than jest 24?

2024-08-30 18:58 UTC, michaelfaith commented on __tests__/src/rules/no-static-element-interactions-test.js
> -  { code: '<link onClick={() => {}} href="#" />;' },
Interesting.  You're right.  Looks like it was a rebasing issue.  Those were added in https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/commit/75d5dd722bd67186d97afa7b151fd6fee5885c70#diff-b8a286945cae1102f315e16a85e3de23850073d6532bb969c8363bc98d61aa20 after this branch was originally created.  I had an issue where my vscode formatted this file, so I while trying to roll that back, I must have replace it with an earlier commit. I'll address this

2024-08-30 19:04 UTC, michaelfaith commented on __tests__/src/rules/no-static-element-interactions-test.js
> -  { code: '<link onClick={() => {}} href="#" />;' },
Fixed.  Though there was one legit removal `<div onClick={() => {}} />`

2024-08-30 19:05 UTC, ljharb commented on package.json
> +    "jest": "^29.7.0",
at some point we'll have a breaking change that drops older eslints/nodes, but i'm more likely to bail on jest entirely and use something less frictiony regardless.

can you map `node:fs/promises` to `fs/promises`, instead? the `node:` prefix is pretty useless.

2024-08-30 20:15 UTC, michaelfaith commented on package.json
> +    "jest": "^29.7.0",
After a few iterations, I got it working.  I ended up having to map several built in no modules, as well as a couple of esm entry points of eslint packages, I also had to add a polyfill for `structuredClone`, which eslint uses as part of `RuleTester` and was added in node 17.

2024-08-30 20:33 UTC, michaelfaith commented on package.json
> +    "jest": "^29.7.0",
Well, it cleared up everything locally, but it's breaking like hell in CI now.

2024-08-30 21:09 UTC, michaelfaith commented on package.json
> +    "jest": "^29.7.0",
Even walking through the steps in CI, locally, still works.  The main difference, though, is I'm on a Windows machine. But that shouldn't come into play here.

2024-08-31 06:39 UTC, pauliesnug commented on package.json
> +    "jest": "^29.7.0",
honestly i don't know anyone who uses anything older than node 16 at this point. it's standard to have deprecated support for older versions, and would make things a lot easier with vitest and the sorts

2024-08-31 12:25 UTC, michaelfaith commented on package.json
> +    "jest": "^29.7.0",
What if we dynamically installed jest 29 in ci for eslint 9, in the same way we're dynmically installing all of the supported eslint versions?  That way we don't have to set up all of this hacky stuff?

2024-08-31 12:49 UTC, michaelfaith commented on package.json
> +    "jest": "^29.7.0",
Actually, I think I got it working.

2024-08-31 19:31 UTC, michaelfaith commented on package.json
> +    "jest": "^29.7.0",
Everything's green now, if you want to take another look when you have the time.  It may be worth considering, dynamically installing a newer jest for v9 and removing all of those workarounds (in the same way each eslint version is being installed), but I'll leave that up to you.

2024-09-01 00:34 UTC, ljharb commented on package.json
> +    "core-js": "^3.38.1",
is there a smaller package we could get a structuredClone polyfill from?

2024-09-01 01:06 UTC, michaelfaith commented on __tests__/__util__/nodeReexports/assert.js
> +export default assert;
That violates an eslint rule in the project.  I could turn the rule off and change those, if you want.  I was just trying to abide by the project's linting rules. 
![image](https://github.com/user-attachments/assets/a0d5d991-a5ae-456b-8fae-bcae10c5a2f4)

2024-09-01 01:07 UTC, michaelfaith commented on package.json
> +    "core-js": "^3.38.1",
https://www.npmjs.com/package/@ungap/structured-clone would work, if you prefer it.

2024-09-01 01:09 UTC, michaelfaith commented on package.json
> +    "pretest": "npx eslint@8 --ext=js,mjs,cjs,ts,tsx . --fix && npm run flow",
Done

2024-09-01 01:27 UTC, ljharb commented on __tests__/__util__/nodeReexports/assert.js
> +export default assert;
ah, yeah this is the special case that rule should allow :-) not a huge deal either way, since I’m probably going to ditch jest and will be able to delete the mocks.

2024-09-01 17:08 UTC, michaelfaith commented on package.json
> +    "core-js": "^3.38.1",
swapped `core-js` for `@ungap/structured-clone`

2024-09-01 17:13 UTC, michaelfaith commented on package.json
> +    "core-js": "^3.38.1",
Swapped back.  that package uses `globalThis` which isn't available in earlier node versions.  `core-js` is the best option here

2024-09-01 21:17 UTC, ljharb commented on package.json
> +    "core-js": "^3.38.1",
ok, this is just another reason to drop jest :-)

2024-09-01 21:18 UTC, ljharb approved these changes
Seems good!

2024-09-01 22:08 UTC, merged

2024-09-04 01:33 UTC, iamtomcat commented
When is this going out? Currently just using it from the repository directly.

2024-09-04 04:31 UTC, ljharb commented
@iamtomcat i'm not sure how you'd do that in a practical sense, since we have a build process. It's only been 2 days - I'd suggest not using it at all until it's published.

2024-09-04 07:15 UTC, iamtomcat commented
Hey @ljharb I appreciate you getting the change out, I wasn't trying to rush you, just wanted to get a time frame was all.

Thanks again.

2024-09-04 07:20 UTC, ljharb commented
it's now released; v6.10.0.

2024-09-12 18:31 UTC, ruiaraujo012 commented
@ljharb I think something is missing, there's no `v6.10.0` release.

2024-09-12 19:02 UTC, ljharb commented
oh thanks, i always forget github releases (which don't matter; only npm matters)