[Deps] Remove polyfills
jsx-eslint/eslint-plugin-jsx-a11y pull request #1020
Opened 2024-10-20 23:54 UTC by talentlessguy

TODO:

- [x] array-includes
- [ ] array.prototype.flatmap
- [ ] object.fromentries
- [ ] string.prototype.includes
- [ ] es-iterator-helpers (not sure about that one fully)

2024-10-21 23:36 UTC, ljharb commented
I pushed up my in-progress `breaking` branch, and rebased this PR on top of it.

2024-10-21 23:45 UTC, ljharb approved these changes
Thanks!

2024-10-21 23:46 UTC, ljharb commented
(don't worry about the test failures; i think they're coming from the `breaking` branch. i'll rebase this and merge it into the breaking branch once things are passing)

2024-10-25 01:33 UTC, MichaelDeBoey approved these changes

2024-10-25 01:51 UTC, MichaelDeBoey requested changes

2024-10-25 01:51 UTC, MichaelDeBoey commented on src/util/isNonInteractiveElement.js
> +const nonInteractiveElementAXObjectSchemas = [...elementAXObjects].flatMap(([elementSchema, AXObjectsArr]) => (AXObjectsArr.every((role): boolean => nonInteractiveAXObjects.has(role)) ? [elementSchem
```suggestion
const nonInteractiveElementAXObjectSchemas = elementAXObjects.flatMap(([elementSchema, AXObjectsArr]) => (AXObjectsArr.every((role): boolean => nonInteractiveAXObjects.has(role)) ? [elementSchema] : []));
```

2024-10-25 01:51 UTC, MichaelDeBoey commented on src/util/isInteractiveElement.js
> +const interactiveElementAXObjectSchemas = [...elementAXObjects].flatMap(([elementSchema, AXObjectsArr]) => (AXObjectsArr.every((role): boolean => interactiveAXObjects.has(role)) ? [elementSchema] : [
```suggestion
const interactiveElementAXObjectSchemas = elementAXObjects.flatMap(([elementSchema, AXObjectsArr]) => (AXObjectsArr.every((role): boolean => interactiveAXObjects.has(role)) ? [elementSchema] : []));
```

2024-10-25 01:54 UTC, ljharb commented on src/util/isNonInteractiveElement.js
> +const nonInteractiveElementAXObjectSchemas = [...elementAXObjects].flatMap(([elementSchema, AXObjectsArr]) => (AXObjectsArr.every((role): boolean => nonInteractiveAXObjects.has(role)) ? [elementSchem
I don't think node 20 has iterator helpers yet, just 22+.

2024-10-25 01:55 UTC, ljharb commented on src/util/isInteractiveElement.js
> +const interactiveElementAXObjectSchemas = [...elementAXObjects].flatMap(([elementSchema, AXObjectsArr]) => (AXObjectsArr.every((role): boolean => interactiveAXObjects.has(role)) ? [elementSchema] : [
elementAXObjects is a Set, and doesn't have flatMap.

2024-10-25 02:13 UTC, MichaelDeBoey approved these changes

2024-10-25 03:34 UTC, ljharb approved these changes
rebased, and will merge into the `breaking` branch. thanks!

2024-10-25 09:47 UTC, MichaelDeBoey approved these changes

2024-10-25 11:44 UTC, MichaelDeBoey commented on src/rules/no-interactive-element-to-noninteractive-role.js
> +
This line seems to fail in CI because of `flow` not recognizing `Object.hasOwn` (yet).

So I guess we should update `flow` first?

2024-10-25 13:04 UTC, talentlessguy commented on src/rules/no-interactive-element-to-noninteractive-role.js
> +
yes, I updated it in the PR but my commit for upgrading it was removed

2024-10-25 13:08 UTC, MichaelDeBoey commented on src/rules/no-interactive-element-to-noninteractive-role.js
> +
@talentlessguy Can you please add it again?

Would love to get this PR merged 🤩

2024-10-25 13:08 UTC, MichaelDeBoey commented on src/util/isNonInteractiveElement.js
> +const nonInteractiveElementAXObjectSchemas = [...elementAXObjects].flatMap(([elementSchema, AXObjectsArr]) => (AXObjectsArr.every((role): boolean => nonInteractiveAXObjects.has(role)) ? [elementSchem
@talentlessguy This suggestion is invalid as well, so please revert

2024-10-25 13:08 UTC, ljharb commented on src/rules/no-interactive-element-to-noninteractive-role.js
> +
my bad, will restore.

2024-10-25 13:09 UTC, talentlessguy commented on src/rules/no-interactive-element-to-noninteractive-role.js
> +
yeah sure

2024-10-25 13:31 UTC, MichaelDeBoey requested changes

2024-10-25 13:31 UTC, MichaelDeBoey commented on src/util/isNonInteractiveElement.js
> +const nonInteractiveElementAXObjectSchemas = elementAXObjects.flatMap(([elementSchema, AXObjectsArr]) => (AXObjectsArr.every((role): boolean => nonInteractiveAXObjects.has(role)) ? [elementSchema] :
@talentlessguy This suggestion was invalid as well, so please revert

```suggestion
const nonInteractiveElementAXObjectSchemas = [...elementAXObjects].flatMap(([elementSchema, AXObjectsArr]) => (AXObjectsArr.every((role): boolean => nonInteractiveAXObjects.has(role)) ? [elementSchema] : []));
```

2024-10-25 13:42 UTC, talentlessguy commented
@ljharb @MichaelDeBoey CI is green now, safe to merge?

2024-10-25 22:58 UTC, merged