Add glob support for label-has-associated-control rule
jsx-eslint/eslint-plugin-jsx-a11y pull request #749
Opened 2020-10-08 15:20 UTC by hallzac2

### Description
Add glob support for label-has-associated-control rule. This will allow consumers of this library to have some more powerful matching capabilities when using the `controlComponents` option.

To accomplish this, I brought in the `micromatch` library => https://github.com/micromatch/micromatch

There are tons of other libraries to do this same thing. It shouldn't be too hard to switch to any of the others if preferred or a lightweight implementation could be done to support the bare minimum.

### Testing
Pull the branch
Run `npm i`
Run `npm run test`
Try out some different globs to ensure that this meeting the feature set that it should be

2020-10-08 17:10 UTC, hallzac2 commented
It looks like the build is failing for older version of node 😦 I looked at `micromatch`'s node engine and it lists `"node": ">=8.6"` so it won't work with this. I'll see if I can find a different solution.

2020-10-08 17:41 UTC, hallzac2 commented
I switched to using `minimatch` since it should be compatible. The build is now passing! 😄

2020-10-10 20:47 UTC, ljharb requested changes
Seems good overall, just a few comments.

2020-10-10 20:47 UTC, ljharb commented on docs/rules/label-has-associated-control.md
> +`controlComponents` is a list of custom React Components names that will output an input element. Glob format is also supported for names.
let's add some examples, or a link to what "glob format" means.

2020-10-10 20:47 UTC, ljharb commented on __tests__/src/util/mayContainChildComponent-test.js
> +  describe('Glob name matching', () => {
```suggestion

  describe('Glob name matching', () => {
```

2020-10-10 20:47 UTC, ljharb commented on __tests__/src/util/mayContainChildComponent-test.js
> +    describe('component name contains asterisk * - match zero or more characters', () => {
```suggestion
    });

    describe('component name contains asterisk * - match zero or more characters', () => {
```

2020-10-12 04:59 UTC, jessebeach commented
Seems really close but for a few nits.

2020-11-02 15:53 UTC, hallzac2 commented
@ljharb I incorporated the requested changes and add documentation / examples for glob format. Sorry about the long turn around time on this, life got a little hectic the past few weeks.

2020-11-28 22:21 UTC, jessebeach commented
> @ljharb I incorporated the requested changes and add documentation / examples for glob format. Sorry about the long turn around time on this, life got a little hectic the past few weeks.

No need to apologize! This is open source; we're all volunteering our time. Thank you for circling back to this one!

2020-11-28 22:22 UTC, jessebeach approved these changes

2020-11-28 22:23 UTC, jessebeach commented
@ljharb good to go?

2020-12-26 17:48 UTC, ljharb approved these changes
Also sorry for the delay on my end :-)

2020-12-26 17:53 UTC, merged