feat: support ESLint 8.x
jsx-eslint/eslint-plugin-jsx-a11y pull request #810
Opened 2021-08-29 16:35 UTC by MichaelDeBoey

ESLint has released the first beta versions of v8 🎉
https://eslint.org/blog/2021/08/eslint-v8.0.0-beta.0-released
https://eslint.org/blog/2021/08/eslint-v8.0.0-beta.1-released

devDependency compatibility with ESLint 8:

- [ ] [`eslint-config-airbnb-base`](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base) (https://github.com/airbnb/javascript/issues/2463)
  - [ ] PR
  - [ ] Release
- [ ] [`eslint-plugin-flowtype`](https://github.com/gajus/eslint-plugin-flowtype) (https://github.com/gajus/eslint-plugin-flowtype/issues/495)
  - [ ] https://github.com/gajus/eslint-plugin-flowtype/pull/496
  - [ ] Release
- [ ] [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import) (https://github.com/import-js/eslint-plugin-import/issues/2211)
  - [ ] https://github.com/import-js/eslint-plugin-import/pull/2191
  - [ ] Release

---

Closes #809

2021-08-29 16:51 UTC, ljharb requested changes

2021-08-29 16:51 UTC, ljharb commented on .eslintrc
> +  parser: "@babel/eslint-parser",
why is this required?

2021-08-29 16:51 UTC, ljharb commented on .github/workflows/node-4+.yml
> +        eslint: ['^8.0.0-0', 7, 6, 5, 4, 3]
please revert this to the multiline array form

2021-08-29 16:55 UTC, MichaelDeBoey commented on .eslintrc
> +  parser: "@babel/eslint-parser",
`babel-eslint` is deprecated in favor of `@babel/eslint-parser`

2021-08-29 18:41 UTC, ljharb commented on .eslintrc
> +  parser: "@babel/eslint-parser",
Sure but why does that matter for eslint 8 support?

2021-08-30 00:08 UTC, MichaelDeBoey commented on .eslintrc
> +  parser: "@babel/eslint-parser",
As I updated all ESLint-related dependencies, I updated this one too.

I can revert if you want, but I think it's better to be at latest version for convenience

2021-08-30 04:45 UTC, ljharb commented on .eslintrc
> +  parser: "@babel/eslint-parser",
I think that should be done separately.

changing how the project is built can have unintended breaking changes, and "convenience" isn't a compelling argument imo.

2021-08-30 08:13 UTC, MichaelDeBoey commented on .eslintrc
> +  parser: "@babel/eslint-parser",
Will create a separate PR for it then 👍

2021-08-30 08:21 UTC, MichaelDeBoey commented on .eslintrc
> +  parser: "@babel/eslint-parser",
https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/811

2021-10-31 22:37 UTC, nschonni commented on .github/workflows/node-4+.yml
> +          - node-version: 13
This aren't supported by 8 https://github.com/eslint/eslint/pull/14592

2021-11-08 09:25 UTC, PodaruDragos commented
is there anything that's blocking this ?

2021-11-09 19:18 UTC, ljharb commented
@PodaruDragos at the time you asked, yes. now, no.

2021-11-10 07:21 UTC, ljharb approved these changes

2021-11-10 07:34 UTC, merged