test: align usage of jest expect across tests
jsx-eslint/eslint-plugin-jsx-a11y pull request #827
Opened 2021-11-27 08:36 UTC by armano2

2021-11-27 16:02 UTC, ljharb requested changes

2021-11-27 16:02 UTC, ljharb commented on package.json
> -    "expect": "^24.9.0",
Using the package and the explicit imports are quite intentional; being more coupled to jest is undesirable.

2021-11-27 16:02 UTC, ljharb commented on __tests__/src/util/isNonInteractiveRole-test.js
> +/* eslint-env jest */
This should really be done with overrides in eslintrc, not in a comment per file.

2021-11-27 17:11 UTC, armano2 commented on package.json
> -    "expect": "^24.9.0",
ok, previously `expect` was not always imported, now it should be consistent

2021-11-27 17:11 UTC, armano2 commented on __tests__/src/util/isNonInteractiveRole-test.js
> +/* eslint-env jest */
done

2022-02-06 23:56 UTC, jessebeach commented
@ljharb looks like your requested changes were made. Shall we get this landed?

2022-02-06 23:56 UTC, jessebeach approved these changes
lgtm, thanks @armano2 !!

2022-02-07 05:30 UTC, ljharb approved these changes

2022-02-07 05:35 UTC, merged