New rule: prefer-tag-over-role
jsx-eslint/eslint-plugin-jsx-a11y pull request #833
Opened 2022-02-24 00:08 UTC by JoshuaKGoldberg

Fixes #101

2022-02-24 00:23 UTC, JoshuaKGoldberg commented on package.json
> +    "jest2": "jest --coverage __tests__/**/*"
whoops 😄 

```suggestion
    "jest": "jest --coverage __tests__/**/*"
```

2022-02-24 19:10 UTC, ljharb approved these changes
Seems pretty straightforward

2022-02-24 19:10 UTC, ljharb commented on __tests__/src/rules/prefer-tag-over-role-test.js
> +    `Use <${tag}> instead of the "${role}" role to ensure accessibility across all devices.`,
```suggestion
  message: `Use <${tag}> instead of the "${role}" role to ensure accessibility across all devices.`,
```
i smell in-editor prettier :-p

2022-07-19 17:04 UTC, jessebeach requested changes
It's a good rule. Thank you for proposing it. I just have a few improvements that will use our utilities and provide more robustness.

2022-08-07 18:16 UTC, jessebeach requested changes
This is really close!! Just a few polishing tweaks to get it over the line! I think we'll be able to commit it after these few changes.

2022-08-07 18:16 UTC, jessebeach commented on src/rules/prefer-tag-over-role.js
> +      if (matchedNames.some((matchedTag) => matchedTag === node.name.name)) {
Use the `getElementType` util here instead of referencing `node.name.name` directly. `getElementType` deals with configured Component names as well as namespaces: 

1. Implementation example: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/7f6463e5cffd1faa5cf22e3b0d33465e22bd10e1/src/rules/no-static-element-interactions.js#L56
2. Definition: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/7f6463e5cffd1faa5cf22e3b0d33465e22bd10e1/src/util/getElementType.js
3. jsx-ast-utils source for reference: https://github.com/jsx-eslint/jsx-ast-utils/blob/main/src/elementType.js

2022-08-07 18:16 UTC, jessebeach commented on src/rules/prefer-tag-over-role.js
> +  'Use {{tag}} instead of the "{{role}}" role to ensure accessibility across all devices.';
`tag` should include attributes if necessary. For example, `<a>` is semantically an anchor on a page, but `<a href>` is a link. `<input>` default to `textbox`, whereas `<input type="checkbox`>` is a checkbox. The recommendation here should be as specific as possible. `roleElements` will give you the `attributes` associated with the tag name, so you can build this string with maximum detail.

2022-08-07 18:16 UTC, jessebeach commented on __tests__/src/rules/prefer-tag-over-role-test.js
> +ruleTester.run("element-rol", rule, {
nit: "element-role"

2022-08-07 18:16 UTC, jessebeach commented on __tests__/src/rules/prefer-tag-over-role-test.js
> +ruleTester.run("element-rol", rule, {
Please add tests for multiple roles, such as `<div role="button checkbox">`. I think your rule will fail in this case. The last role in a space-delimited list will be the one that applies.

2022-08-07 18:57 UTC, JoshuaKGoldberg commented on src/rules/prefer-tag-over-role.js
> +      if (matchedNames.some((matchedTag) => matchedTag === node.name.name)) {
Love it, thanks!

2022-08-07 18:58 UTC, JoshuaKGoldberg commented on __tests__/src/rules/prefer-tag-over-role-test.js
> +ruleTester.run("element-rol", rule, {
TIL!

2022-08-07 20:56 UTC, jessebeach approved these changes
Thank you for the updates!

@ljharb looks good to ship!

2022-08-07 20:57 UTC, jessebeach commented
There's still a little work to expose the rule through the plugin, but this is good enough to get the rule logic into the code.

2022-08-07 20:57 UTC, merged

2022-08-07 20:58 UTC, jessebeach commented
Thanks @JoshuaKGoldberg for proposing and writing this rule!

2022-08-07 20:59 UTC, JoshuaKGoldberg commented
Thanks for the helpful+informative reviews @jessebeach!

And oops, I didn't think to add to the plugin rules & recommended sets. I can send a PR now.

2022-10-27 03:52 UTC, ljharb commented
@JoshuaKGoldberg somehow we all totally missed the docs for this rule - could you send a PR to add them?