New rule: alt-text-max-length
jsx-eslint/eslint-plugin-jsx-a11y pull request #834
Opened 2022-02-24 01:02 UTC by JoshuaKGoldberg

Fixes #264

2022-02-24 04:31 UTC, ljharb commented on __tests__/src/rules/alt-text-max-length-test.js
> +      code: `<img alt="${new Array(126).fill('x').join('')}" />`,
I’m confused how this one works; are we hardcoding support for the bad practice of using new Array with fill?

2022-02-24 11:12 UTC, JoshuaKGoldberg commented on __tests__/src/rules/alt-text-max-length-test.js
> +      code: `<img alt="${new Array(126).fill('x').join('')}" />`,
It's just for the test case to make it obvious there are 126 `x` characters. The code is equivalent to:

```
<img alt="xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx" />
```

2022-02-24 14:46 UTC, ljharb commented on __tests__/src/rules/alt-text-max-length-test.js
> +      code: `<img alt="${new Array(126).fill('x').join('')}" />`,
ahhh right, thanks

2022-02-24 14:47 UTC, ljharb commented on __tests__/src/rules/alt-text-max-length-test.js
> +      code: `<img alt="${new Array(126).fill('x').join('')}" />`,
```suggestion
      code: `<img alt="${Array.from({ length: 126 }, () => 'x').join('')}" />`,
```

2022-02-24 16:34 UTC, uncommon-type commented on docs/rules/alt-text-max-length.md
> +Screenreaders typically stop reading alt text after 100-150 characters.
Hi @JoshuaKGoldberg, there’s a fresh [blog post](https://yatil.net/blog/there-is-no-character-limit-for-alt-text) by Eric Eggert about how there’s no hard limit for alternative text length. Might be worth checking it out?

2022-02-24 19:04 UTC, uncommon-type commented on docs/rules/alt-text-max-length.md
> +Screenreaders typically stop reading alt text after 100-150 characters.
> Dang, just when I thought I'd gotten up-to-date 😄

I just thought I should let you know 😄  probably, rewording it could help

2022-02-24 19:15 UTC, JoshuaKGoldberg commented on docs/rules/alt-text-max-length.md
> +Screenreaders typically stop reading alt text after 100-150 characters.
Thanks 💖, reworded!

2022-08-08 20:52 UTC, ljharb requested changes
Before updating this, perhaps https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/264#issuecomment-1050156491 should be responded to?

2022-08-08 20:52 UTC, ljharb commented on src/index.js
> +        'jsx-a11y/alt-text-max-length': 'error',
rules can't be added to the config without it being a breaking change, so these lines should be removed

2022-08-08 20:52 UTC, ljharb commented on src/rules/alt-text-max-length.js
> +      JSXOpeningElement: (node) => {
```suggestion
      JSXOpeningElement(node) {
```

2022-08-09 17:01 UTC, closed without merging

2022-08-09 17:01 UTC, JoshuaKGoldberg commented
Closing per https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/264#issuecomment-1209540959. Thanks for the reviews!