Add CONTRIBUTING.md to solicit contributions
jsx-eslint/eslint-plugin-jsx-a11y pull request #846
Opened 2022-04-03 15:25 UTC by uncommon-type

## Description

This PR adds a CONTRIBUTING.md  to provide potential contributors with a short guide to how to help with the project. It explains the ways to get involved as well as gives setup/installation details and information on how to submit Pull Requests. It also points out that project is covered by `OpenJS Foundation Code of Conduct` to  set the tone for contributions.

## Related Issue

Closes #845 

## Acceptance Criteria

- [x]  Info is included on ways to contribute
- [x]  Details are provided on how to set up dev environment
- [x]  Guidelines are given on how to submits pull requests
- [x] Code of Conduct is mentioned for setting the tone for contributions
- [x] Table of contents is added with links to document headings

## Type of Changes

|     | Type                       |
| --- | -------------------------- |
|    | :bug: Bug fix              |
|    | :sparkles: New feature     |
|    | :hammer: Refactoring       |
|    | :100: Add tests            |
|   | :link: Update dependencies |
|  ✓  | :scroll: Docs              |

2022-04-03 16:31 UTC, ljharb requested changes

2022-04-03 16:31 UTC, ljharb commented on CONTRIBUTING.md
> + You can consider helping out with [issues](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues) already requiring attention.
should this link to the "help wanted" label?

2022-04-03 16:31 UTC, ljharb commented on CONTRIBUTING.md
> +If you run into problems while using  ``eslint-plugin-jsx-a11y``, you can report them by opening a new issue  and providing as much context as you can about what you're running into along with a fail
```suggestion
If you run into problems while using `eslint-plugin-jsx-a11y`, you can report them by opening a new issue and providing as much context as you can about what you're running into, along with a failing test or code sample to help others verify and ultimately fix the issue.
```

2022-04-03 16:31 UTC, ljharb commented on CONTRIBUTING.md
> +> **Note:** Before submitting an issue, please check open and closed issues to see if the problem has already been reported.
```suggestion
> **Note:** Before filing an issue, please check both open and closed issues to see if the problem has already been reported.
```

2022-04-03 16:31 UTC, ljharb commented on CONTRIBUTING.md
> +If you want to propose a new rule, please follow these [instructions](https://eslint.org/docs/developer-guide/contributing/new-rules).
these are eslint core's guidelines - probably worth folks reading, but not necessarily the criteria we'd apply here.

2022-04-03 16:31 UTC, ljharb commented on CONTRIBUTING.md
> +We are happy to welcome contributions  from anyone willing to improve documentation by adding missing information or making it more consistent and coherent.
```suggestion
We are happy to welcome contributions from anyone willing to improve documentation by adding missing information or making it more consistent and coherent.
```

2022-04-03 16:31 UTC, ljharb commented on CONTRIBUTING.md
> +  npm run test
```suggestion
  npm test && npm run build
  ```
* After making changes, verify them and update your code if there’re any failing tests
  ```
  npm run tests-only
```

2022-04-03 16:31 UTC, ljharb commented on CONTRIBUTING.md
> +Before  sending the pull request, make sure your code is running on the latest available code by rebasing onto the upstream source
```suggestion
Before sending the pull request, make sure your code is running on the latest available code by rebasing onto the upstream source
```

2022-04-03 16:31 UTC, ljharb commented on CONTRIBUTING.md
> +
```suggestion
```

2022-04-03 16:31 UTC, ljharb commented on CONTRIBUTING.md
> +    * `perf`  a code change that improves performance
these are angular's/conventional-commit's commit message conventions, and i don't use them. in particular, i'm philosophically opposed to "chore" - chores are bad, repo maintenance is good.

my commit conventions are undocumented but somewhat consistent. i suppose i should probably document them in a gist, and then we can link to that here.

2022-04-03 16:31 UTC, ljharb commented on CONTRIBUTING.md
> +We adhere to the [OpenJS Foundation Code of Conduct](https://github.com/openjs-foundation/cross-project-council/blob/main/CODE_OF_CONDUCT.md) and expect
this is a great idea, but we don't actually adhere to that in this github org yet. we could add a CODE_OF_CONDUCT.md file to https://github.com/jsx-eslint/.github, though, and then we don't need to mention it here at all.

2022-04-04 15:30 UTC, uncommon-type commented on CONTRIBUTING.md
> +    * `perf`  a code change that improves performance
I've seen those listed on the ESLint website, this is why I've included them here😄. Will remove them for now and wait for your gist.

2022-04-05 07:56 UTC, uncommon-type commented on CONTRIBUTING.md
> +If you want to propose a new rule, please follow these [instructions](https://eslint.org/docs/developer-guide/contributing/new-rules).
thank you for pointing out, I removed the reference😄

2022-04-07 05:07 UTC, ljharb commented
This is pending https://github.com/jsx-eslint/.github/pull/1.

2022-04-15 16:43 UTC, ljharb approved these changes
Thanks!

2022-04-15 17:00 UTC, merged