New rule: ambiguous-anchor-text
jsx-eslint/eslint-plugin-jsx-a11y pull request #873
Opened 2022-07-11 22:56 UTC by mattxwang

This is a draft PR to add a new rule `ambiguous-anchor-text`. I've architected the bare minimum rule implementation (i.e. only trivial cases) and some documentation. I'm opening this as a draft as I want to get feedback on various areas (this is my first time contributing to this repo):

- I will likely eventually move `combineChildText` into its own file. before doing so:
  - thoughts on the name?
  - how would I know which AST nodes I should be "combining"? should I be calling this recursively on `JSXElement`s (I think I want to)? What about getting the `aria` text for various variables? this is something I have low visibility in, and am struggling to figure out where to look for more information on the AST.
- what other test cases should I add? One I'm looking to do is skipping screenreader-hidden elements; any other ones?
- how is the documentation? is it the right level of conciseness, clarity, etc.?

Closes #866.

2022-07-13 04:41 UTC, gaurav5430 commented on src/rules/anchor-ambiguous-text.js
> +    case 'JSXText':
do we need to take care of JSXElement here ?

```
<a ...> Click <span> here </span> </a>
```

2022-07-13 04:42 UTC, gaurav5430 commented on src/rules/anchor-ambiguous-text.js
> +        context.report({
just checking that the text content matches any of the ambiguous text might not be enough, as the author might have already catered for this by adding an aria-label which explains things more clearly.

2022-07-13 04:43 UTC, gaurav5430 commented on src/rules/anchor-ambiguous-text.js
> +];
we can allow passing this list as an option as well , and fallback to this as default ?

2022-07-13 04:45 UTC, ljharb requested changes

2022-07-13 04:45 UTC, ljharb commented on docs/rules/anchor-ambiguous-text.md
> +      "words": [ "click this" ],
```suggestion
    "jsx-a11y/img-redundant-alt": [2, {
      "words": ["click this"],
```

2022-07-13 04:45 UTC, ljharb commented on docs/rules/anchor-ambiguous-text.md
> +The `words` option adds additional strings that can be checked for in the anchor text. Useful for specifying other words in other languages.
why only additional? what if someone doesn't want the default words?

2022-07-13 04:45 UTC, ljharb commented on src/index.js
> +        'jsx-a11y/anchor-ambiguous-text': 'error',
adding a new rule to a config is a breaking change, so we can't do that here.
```suggestion
        'jsx-a11y/anchor-ambiguous-text': 'off', // TODO: error
```

2022-07-13 04:45 UTC, ljharb commented on src/rules/anchor-ambiguous-text.js
> +const errorMessage = `Ambiguous text within anchor. Screenreader users rely on link text for context; the words ${AMBIGUOUS_WORDS.join(',')} are ambiguous and do not provide enough context.`;
this error message won't contain the right words if the config specifies its own words

2022-07-13 04:45 UTC, ljharb commented on src/rules/anchor-ambiguous-text.js
> +  }
```suggestion
  if (child.type === 'Literal' || child.type === 'JSXText) {
    return str + child.value;
  }
  return str;
```
switch statements should be avoided :-)

2022-07-13 04:49 UTC, gaurav5430 commented on src/rules/anchor-ambiguous-text.js
> +const combineChildText = (node: JSXElement): string => node.children.reduce((str: string, child: Node) => {
how are you able to use type annotations in js files ?

2022-07-13 04:49 UTC, ljharb commented on src/rules/anchor-ambiguous-text.js
> +const combineChildText = (node: JSXElement): string => node.children.reduce((str: string, child: Node) => {
this project uses flow.

2022-07-13 04:53 UTC, gaurav5430 commented on src/rules/anchor-ambiguous-text.js
> +    case 'JSXText':
```
function getChildText(node) {
  const childText = node.children.reduce((prev, current, index, arr) => {
    switch (current.type) {
      case 'JSXText':
        return prev + current.value;
      case 'JSXElement':
        return prev + getChildText(current);
      default:
        return prev;
    }
  }, '');

  return childText;
}
```

2022-07-13 16:26 UTC, mattxwang commented on src/index.js
> +        'jsx-a11y/anchor-ambiguous-text': 'error',
Ah, I see. This portion was auto-generated with the new rule script (i.e. `./scripts/create-rule.js`), so maybe that needs to be updated too?

2022-07-13 16:27 UTC, mattxwang commented on docs/rules/anchor-ambiguous-text.md
> +The `words` option adds additional strings that can be checked for in the anchor text. Useful for specifying other words in other languages.
I based this off of `img-redundant-alt`, which has the same interface. I can certainly switch to letting the user override the defaults as well!

2022-07-13 16:28 UTC, mattxwang commented on src/rules/anchor-ambiguous-text.js
> +    case 'JSXText':
I think we do, yup! The current `switch-case` (or eventual `if` statement given the other cr feedback) is not comprehensive for sure. Do you know if there's a list of all AST elements? I was trying to find one but wasn't particularly successful.

2022-07-13 16:29 UTC, mattxwang commented on src/rules/anchor-ambiguous-text.js
> +        context.report({
Agreed, let me see if I can also check for that too!

2022-07-13 16:29 UTC, mattxwang commented on src/rules/anchor-ambiguous-text.js
> +];
Agreed given feedback from @ljharb below as well.

2022-07-13 16:32 UTC, ljharb commented on src/rules/anchor-ambiguous-text.js
> +const errorMessage = `Ambiguous text within anchor. Screenreader users rely on link text for context; the words ${AMBIGUOUS_WORDS.join(',')} are ambiguous and do not provide enough context.`;
An alternative is to use eslint's message substitution and sub in the words

2022-07-13 16:32 UTC, ljharb commented on src/index.js
> +        'jsx-a11y/anchor-ambiguous-text': 'error',
agreed

2022-07-13 18:49 UTC, mattxwang commented
Had a chance to also chat offline with some folks at CZI (including Andrew Huth!) about suggested improvements; want to document them here for posterity:

- let `aria-label` supersede internal text
- add `"learn more"` as a default ambiguous word, which in turn would adjust one of the "accepted" test cases to being a failure
- stretch goal: for elements with `aria-labelledby`, traverse children/related nodes to see if the `id`'d element exists and use its text. This may be too much of a performance hit/out of scope for the rule, and has problems if the labelledby element either doesn't exist or is not in the direct tree of the element.

@ljharb @gaurav5430 any thoughts? I'll try to wrap up implementing your suggestions as well sometime today/tomorrow, work schedule permitting.

cc: @dierat @jinlee93 @ahuth @jeremiah-clothier

2022-07-13 22:41 UTC, mattxwang commented
I think I've addressed the initial round of feedback (I'm not sure why the rebase action is failing - I've merged `main` into the branch). Haven't yet moved `getAccessibleChildText` into its own file yet, but I'll do that once we finalize the general operational feedback + write some specific tests for it.

Wanted to ask about:

- the `aria-labelledby` idea noted above
- should something like `<a><img alt="click here /></a>` be in scope of this rule?
- the general points of feedback I listed above

2022-07-18 23:07 UTC, mattxwang commented
Hi all, just wanted to see if y'all had any more feedback. If not, I'll move `getAccessibleChildText` into its own file, write a couple of tests, and then mark this as ready for review.

2022-07-19 22:47 UTC, ljharb reviewed
This seems great overall.

Can we ensure that this works with the "components" setting? iow, if someone has mapped `CustomLink` to `a`, it should warn on CustomLink elements also.

2022-07-19 22:47 UTC, ljharb commented on src/rules/anchor-ambiguous-text.js
> +          message: errorMessage,
```suggestion
        context.report({
          node,
          message: 'Ambiguous text within anchor. Screenreader users rely on link text for context; the words "{{wordsList}}" are ambiguous and do not provide enough context.',
          data: {
            wordsList: words.join('", "'),
          },
```

2022-07-19 23:21 UTC, mattxwang commented
> Can we ensure that this works with the "components" setting? iow, if someone has mapped `CustomLink` to `a`, it should warn on CustomLink elements also.

@ljharb I think I've added a test case for that already, this is [lines 65-69](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/873/files#diff-ac389cac751fa3edfe0e50ee6577beb824be48e326053c0194373fd23e633320R65-R69) in the test code:

```
    {
      code: '<Link>here</Link>',
      errors: [expectedError],
      settings: { 'jsx-a11y': { components: { Link: 'a' } } },
    },
```

Or did you mean something else?

2022-07-21 03:49 UTC, ljharb reviewed
Almost there :-)

2022-07-21 03:49 UTC, ljharb commented on src/rules/anchor-ambiguous-text.js
> +        const ambiguousWords = new Set(words);
these, and the options extraction, should be done at the top level of `create` to avoid having to do so every time the node is visited.

2022-07-21 03:49 UTC, ljharb commented on __tests__/src/rules/anchor-ambiguous-text-test.js
> +      settings: { 'jsx-a11y': { components: { Link: 'a' } } },
can you add a valid test using `components` as well?

2022-07-21 03:49 UTC, ljharb commented on src/util/getAccessibleChildText.js
> +  )) return '';
```suggestion
  if (
    isHiddenFromScreenReader(
      elementType(node.openingElement),
      node.openingElement.attributes
    )
  ) {
    return '';
  }
```

2022-07-21 18:20 UTC, ljharb commented on src/util/getAccessibleChildText.js
> +  )) return '';
We don't use prettier, thankfully :-) but yes, being able to disallow multiline constructs from not being on their own line would be a great rule that the airbnb config would adopt.

2022-07-21 18:25 UTC, mattxwang commented
Thanks for the feedback @ljharb, I think I've addressed all of it in the last two commits!

2022-07-21 18:55 UTC, ljharb approved these changes
Thanks!

2022-07-21 19:01 UTC, mattxwang commented
Just updated the branch from `main`. I'm not sure why the automatic rebase action is failing.

Re: "stretch" goal features (ex traversing the tree for `aria-labelledby`, `alt` text in images, etc.), should I open another issue to follow up? Certainly something I can do!

2022-07-21 20:00 UTC, ljharb commented
Don't worry about the rebase one :-)

Another issue (or PR, if you're ambitious) would be most appreciated.

2022-07-21 20:12 UTC, merged

2022-07-21 22:15 UTC, mattxwang commented
> Another issue (or PR, if you're ambitious) would be most appreciated.

Sounds good, and I'd be happy to at the very least write up an issue (I'll try my hand at a PR, but no promises). I'll aim to get one in over the next day or two!