[New] disallow `aria-hidden="true"` on focusable elements
jsx-eslint/eslint-plugin-jsx-a11y pull request #888
Opened 2022-08-26 22:35 UTC by khiga8

Fixes: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/881

This adds a new rule that flags when `aria-hidden="true"` is set on focusable elements or contain child elements that are focusable. People often set `aria-hidden="true"` to hide an element from AT users, but if the element is focusable, AT users can still access it which can be confusing.

I wasn't sure what the contributing process is like so wanted to get a draft PR going to get thoughts. I looked through the list of jsx-a11y rules and I couldn't find a rule for something like this but let me know if I missed it. If maintainers are okay moving forward with this, I will add a doc page. I've ran the lint and tests.

Related: 
- [aria-hidden elements do not contain focusable elements](https://dequeuniversity.com/rules/axe/html/4.4/aria-hidden-focus)
- [Element with aria-hidden has no content in sequential focus navigation](https://www.w3.org/WAI/standards-guidelines/act/rules/6cfa84/proposed/)

2022-08-26 22:41 UTC, ljharb reviewed
Seems good overall.

2022-08-26 22:41 UTC, ljharb commented on src/rules/no-aria-hidden-on-focusable.js
> +      JSXOpeningElement: (node) => {
```suggestion
      JSXOpeningElement(node) {
```

2022-08-26 22:41 UTC, ljharb commented on src/rules/no-aria-hidden-on-focusable.js
> +  create: (context) => {
```suggestion
  create(context) {
```

2022-08-26 22:41 UTC, ljharb commented on __tests__/src/rules/no-aria-hidden-on-focusable-test.js
> +    // { code: '<textarea aria-hidden="true" />', errors: [expectedError] },
can these be uncommented?

2022-08-26 22:42 UTC, khiga8 commented on __tests__/src/rules/no-aria-hidden-on-focusable-test.js
> +    // { code: '<textarea aria-hidden="true" />', errors: [expectedError] },
Ah I was trying to debug a test. sorry about that.

2022-08-26 23:26 UTC, khiga8 commented
Added more test cases and fixed a bug in [bc220ad](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/888/commits/bc220adf8efe3f594d1375573b84f0c64fcf2b9a).

Added a doc page in [e96c9db](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/pull/888/commits/e96c9db87f52d17151c7718202c256e871b3202d).

2022-08-26 23:54 UTC, ljharb commented on src/rules/no-aria-hidden-on-focusable.js
> +  return (tabIndex !== -1 && isInteractiveElement(type, attributes)) || (tabIndex !== undefined && tabIndex !== -1);
```suggestion
  return tabIndex !== -1 && (
    tabIndex !== undefined
    || isInteractiveElement(type, attributes)
  );
```

2022-08-26 23:54 UTC, ljharb commented on src/rules/no-aria-hidden-on-focusable.js
> +        });
```suggestion
        children.filter((child) => {
          if (child.type !== 'JSXElement' || !child.openingElement) {
            return false;
          }
          const openingChildElement = child.openingElement;
          const childType = elementType(openingChildElement);
          const childAttributes = openingChildElement.attributes;
          return isFocusable(childType, childAttributes);
        }).forEach((child) => {
          context.report({
            node: child.openingElement,
            message: errorMessage,
          });
        });
```

2022-08-27 01:03 UTC, jessebeach requested changes
@khiga8 this is a great idea for a rule. You're off to a solid start. I'd love to move your `isFocusable` function to its own utility. And I have a question about the reason behind traversing child elements. 

I think you can get this to a place where we can get it committed. I look forward to the updates!

2022-08-27 01:03 UTC, jessebeach commented on src/rules/no-aria-hidden-on-focusable.js
> +        const { children } = node.parent;
Generally, you want to use ESLint's visitor pattern to visit nodes, rather than doing your own tree traversal within a rule down into child nodes. What is purpose of creating reports for focusable children of the opening node?

2022-08-27 01:17 UTC, khiga8 commented on src/rules/no-aria-hidden-on-focusable.js
> +        const { children } = node.parent;
Thank you for pointing this out. I'm new to ESLint rule creation so uh.. please excuse my non-idiomatic code 🙇‍♀️.

My intention had been to cover cases where `aria-hidden` is set on an element that contains focusable children like:
```.jsx
<div aria-hidden="true">
   <a href="/">Some site</a>
</div>
```

Is this something that can be accomplished with the visitor pattern? I'll have to do a bit more digging into ESLint conventions.

2022-08-27 17:15 UTC, jessebeach commented on src/rules/no-aria-hidden-on-focusable.js
> +        const { children } = node.parent;
> My intention had been to cover cases where aria-hidden is set on an element that contains focusable children like:

Ok, I understand. For this rule, I'm going to recommend that you keep it narrowly focused to just focusable elements and not their ancestors or descendants. The problem of the cascading effects of aria-hidden on the AX tree is a thorny one and it will complicate a rule that is otherwise straightforward and easy to reason about. Plus, these sorts of tree relationships are hard to lint for, because you're only getting a snippet of the total render tree while linting, so that incidence of positive cases is going to be low with this static linting method. The reason I really like your rule is that it can be narrowly focused to focusable elements and there is good literature about how `aria-hidden` should interact with these.

2022-08-27 17:15 UTC, jessebeach commented on src/rules/no-aria-hidden-on-focusable.js
> +        const { children } = node.parent;
> please excuse my non-idiomatic code 🙇‍♀️

No need for apologies :)

2022-08-31 17:34 UTC, jessebeach approved these changes
This is amazing @khiga8! Thank you so much for proposing this rule and going through the iterations to develop it. Let's get it landed!

2022-08-31 17:34 UTC, jessebeach commented
@ljharb ready to land

2022-08-31 19:53 UTC, ljharb approved these changes

2022-08-31 20:03 UTC, merged