Allow `menuitemradio` and `menuitemcheckbox` on <li>
jsx-eslint/eslint-plugin-jsx-a11y pull request #950
Opened 2023-08-28 16:24 UTC by khiga8

Fixes: https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/issues/896

Currently, the `jsx-a11y/no-noninteractive-element-to-interactive-role` rule flags `<li role="menuitemradio">` and `<li role="menuitemcheckbox">`. I don't think these should be flagged, especially given we allow `<li role="menuitem">`.

Conflicting recommendations:
* [Editor Menubar Example | APG | WAI | W3C](https://www.w3.org/WAI/ARIA/apg/patterns/menubar/examples/menubar-editor/) has an example markup with `<li role="menuitemradio">`. 
* [WAI -ARIA 1.2 Example](https://www.w3.org/TR/wai-aria-1.2/#example-2)
* [WAI-ARIA 1.4 Example](https://www.w3.org/TR/wai-aria-1.2/#example-4)

2023-09-05 00:58 UTC, jessebeach approved these changes
Thank you @khiga8 !

2023-10-30 19:29 UTC, ljharb requested changes
This needs some tests.

2024-05-06 16:59 UTC, khiga8 commented on __tests__/src/rules/no-noninteractive-element-to-interactive-role-test.js
> +    { code: '<li role="menuitemradio" />;' },
I've added the requested test!

2024-05-21 01:32 UTC, ljharb approved these changes

2024-05-21 01:52 UTC, merged