feat: Allow polymorphic linting to be restricted to specified components
jsx-eslint/eslint-plugin-jsx-a11y pull request #984
Opened 2024-05-06 15:03 UTC by khiga8

#### Change

This change allows the consumer to restrict polymorphic linting to a specified list of components via a new setting,`polymorphicAllowList`. When this setting is NOT set (current behavior), then the polymorphic prop will be used for any components with the `polymorphicPropName` present. When this setting is present, then there is an additional check to make sure that the component is part of `polymorphicAllowList`.

#### Motivation

Linting components can raise false positives when a component handles behavior that the linter has no way to know. For example, an `Avatar` component may render as an `img` by default and automatically render an `alt` based on a username. The linter may raise a false positive if `Avatar` is linted as an `img` for the alt text lint rule. This can be avoided by not adding the `Avatar` to the component map. If`Avatar` (for whatever reason) explicitly has `as="img"` set since it can also be rendered as an `svg`, it will end up getting linted via the `polymorphicPropName` setting.

In some projects, polymorphic linting may be useful, but it may be safer to restrict it to utility/basic components that don't do much (e.g. a [generic `Box` element](https://mui.com/material-ui/react-box/)), rather than opening it up to any component that allows the polymorphic prop to be set.

I acknowledge that polymorphism is not an ideal pattern that adds complexity. I do find supporting this feature useful for some components across projects.

2024-05-21 01:59 UTC, ljharb requested changes

2024-05-21 01:59 UTC, ljharb commented on src/util/getElementType.js
> +      }
```suggestion
      if (!polymorphicAllowList || polymorphicAllowList.includes(rawType)) {
        rawType = polymorphicProp;
      }
```

also this needs to use `import includes from 'array-includes';` instead of `.includes`

2024-05-21 02:20 UTC, ljharb commented
we'll also need documentation.

2024-06-19 21:47 UTC, khiga8 commented
This is ready for another review 🙇‍♀️

2024-09-04 05:48 UTC, ljharb approved these changes
i still find polymorphic components horrific, and i hope you're able to fix your codebase by removing them :-) but let's land this

2024-09-04 05:56 UTC, merged